import { join } from 'node:path';
import { existsSync } from 'node:fs';
import { readdir } from 'node:fs/promises';
import { writeFileSafe, projectRoot, readFileSafe } from '../utils/fs.js';
import type { ApplyPlan } from '../core/apply.js';

/**
 * Starters wiring (v0.7) — closes the `plan --apply` gap. Apply writes
 * starter code under .vibe/starters/; this module persists machine-readable
 * wiring instructions next to them so the AI (or human) can integrate them,
 * and lets `status`/MCP report how many steps remain pending.
 */

export interface WiringStep {
  repo: string;
  name: string;
  steps: string[];
  done: boolean;
}

const MARKER_DONE = '<!-- vibe-harness: wiring complete -->';

async function startersDir(root: string): Promise<string> {
  return join(root, '.vibe', 'starters');
}

/** Collect wiring steps from the applied plan and write .vibe/starters/README.md. */
export async function writeStartersReadme(plan: ApplyPlan): Promise<string[]> {
  const steps: WiringStep[] = plan.items
    .filter((i) => (i.recipe.wiring?.length ?? 0) > 0)
    .map((i) => ({ repo: i.entry.repo, name: i.entry.name, steps: i.recipe.wiring ?? [], done: false }));

  if (steps.length === 0) return [];

  const lines: string[] = [
    '# Starters — integration guide',
    '',
    '> Generated by `vibe-harness plan --apply`. Each block below must be',
    '> integrated into the app. Your AI assistant can do this — ask it to',
    '> "wire the VibeHarness starters" and review the diff.',
    '',
  ];
  for (const step of steps) {
    lines.push(`## ${step.name} (\`${step.repo}\`)`, '');
    for (const s of step.steps) lines.push(`- [ ] ${s}`);
    lines.push('');
  }
  lines.push(
    'When every step is done, mark this file complete by keeping the marker below:',
    '',
    MARKER_DONE,
    ''
  );

  await writeFileSafe(join(await startersDir(projectRoot()), 'README.md'), lines.join('\n'), {
    overwrite: true,
    quiet: true,
  });

  return steps.flatMap((s) => s.steps.map((step) => `[${s.name}] ${step}`));
}

export interface StartersStatus {
  pending: boolean;
  readmePath: string | null;
  steps: WiringStep[];
}

/**
 * Read the current starters status for `status`/MCP: pending steps parsed
 * from README.md checkboxes plus any starter files present without a README.
 */
export async function readStartersStatus(): Promise<StartersStatus> {
  const root = projectRoot();
  const dir = await startersDir(root);
  if (!existsSync(dir)) return { pending: false, readmePath: null, steps: [] };

  const readmePath = join(dir, 'README.md');
  const raw = await readFileSafe(readmePath);
  if (!raw) return { pending: true, readmePath: null, steps: [] };
  if (raw.includes(MARKER_DONE) && !raw.includes('- [ ] ')) {
    return { pending: false, readmePath: '.vibe/starters/README.md', steps: [] };
  }

  const steps: WiringStep[] = [];
  let current: WiringStep | null = null;
  for (const line of raw.split('\n')) {
    const heading = line.match(/^## (.+?) \((`[^`]+`)\)/);
    if (heading) {
      current = { repo: heading[2].replace(/`/g, ''), name: heading[1], steps: [], done: false };
      steps.push(current);
      continue;
    }
    const unchecked = line.match(/^- \[ \] (.+)$/);
    if (unchecked && current) current.steps.push(unchecked[1]);
  }

  const pendingSteps = steps.filter((s) => s.steps.length > 0);
  return { pending: pendingSteps.length > 0, readmePath: '.vibe/starters/README.md', steps: pendingSteps };
}

/** List starter files (relative paths) — used by MCP to point the AI at them. */
export async function listStarterFiles(): Promise<string[]> {
  const dir = await startersDir(projectRoot());
  if (!existsSync(dir)) return [];
  const out: string[] = [];
  const walk = async (rel: string): Promise<void> => {
    const entries = await readdir(join(dir, rel), { withFileTypes: true });
    for (const e of entries) {
      const child = rel ? `${rel}/${e.name}` : e.name;
      if (e.isDirectory()) await walk(child);
      else if (e.name !== 'README.md') out.push(`.vibe/starters/${child}`);
    }
  };
  await walk('');
  return out;
}
