export function dependabotTemplate(ecosystems: string[] = ['npm', 'github-actions']): string {
  const blocks = ecosystems
    .map(
      (eco) => `  - package-ecosystem: "${eco}"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10`
    )
    .join('\n');

  return `# Generated by vibe-harness doctor — keeps dependencies fresh.
version: 2
updates:
${blocks}
`;
}
