/**
 * LGPD_POLICY.md template — generated during `npx @vibeharness/cli init`
 * Provides a practical LGPD compliance checklist adapted to the project.
 */
import { sanitizeInline } from '../ui/report.js';

export function lgpdPolicyTemplate(options: {
  projectName: string;
  hasPayments: boolean;
  hasAuth: boolean;
  hasSensitiveData: boolean;
  country: string;
}): string {
  const { projectName, hasPayments, hasAuth, hasSensitiveData, country } = options;
  const safeName = sanitizeInline(projectName);
  const date = new Date().toISOString().split('T')[0];
  const isGlobal = country === 'global';

  return `# LGPD Compliance Guidelines — ${safeName}
> Generated by vibe-harness on ${date}
> Scope: ${isGlobal ? 'Brazil (LGPD) + International (GDPR-aligned)' : 'Brazil — Lei nº 13.709/2018'}
> ⚠️  This document is a compliance checklist — consult a lawyer before going live.

---

## 1. Legal Bases for Processing (Art. 7 / Art. 11 — LGPD)

Before collecting any personal data, identify and document the legal basis:

| Data Type | Legal Basis | Notes |
|-----------|-------------|-------|
| Account registration | Execution of a contract (Art. 7, V) | User creates account to use the service |
| Analytics / Usage | Legitimate interest (Art. 7, IX) | Must not override user rights |
| Marketing e-mails | Consent (Art. 7, I) | Must be freely given, specific, informed |
${hasPayments ? '| Payment processing | Execution of a contract (Art. 7, V) | Required to fulfil purchase |\n' : ''}
---

## 2. Data Inventory (Art. 9 — Transparency)

Document every personal data field collected:

| Field | Purpose | Retention Period | Shared With |
|-------|---------|-----------------|-------------|
| Name | Personalisation | Account lifetime | Nobody |
| E-mail | Authentication, notifications | Account lifetime | E-mail provider |
| IP Address | Security / fraud detection | 90 days | Nobody |
${hasAuth ? '| Password (hashed) | Authentication | Account lifetime | Nobody |\n' : ''}
${hasPayments ? '| Payment data | Process transactions | Legal minimum (5 years) | Payment processor (Stripe/Pagar.me) |\n' : ''}

---

## 3. User Rights Implementation Checklist (Art. 18 — LGPD)

- [ ] **Confirmation & Access** — Users can view all data stored about them \`GET /api/user/data\`
- [ ] **Correction** — Users can update their personal data \`PUT /api/user/profile\`
- [ ] **Anonymisation / Blocking** — Inactive accounts are anonymised after 2 years
- [ ] **Portability** — Users can export their data in JSON/CSV \`GET /api/user/export\`
- [ ] **Deletion (Right to be Forgotten)** — Users can delete their account \`DELETE /api/user\`
- [ ] **Revoke Consent** — Users can withdraw marketing consent at any time
- [ ] **Objection** — Users can object to processing based on legitimate interest

---

## 4. Security Measures (Art. 46 — LGPD)

- [ ] Passwords hashed with bcrypt (cost ≥ 12) or Argon2id — never plaintext
- [ ] All data in transit encrypted with TLS 1.2+
- [ ] PII encrypted at rest (database encryption enabled)
- [ ] Access to production database restricted to named principals only
- [ ] Security incident response plan documented
- [ ] Breach notification process defined (ANPD must be notified within 2 business days of becoming aware of a serious incident)
${hasSensitiveData ? '- [ ] Sensitive data (health, financial, biometric) processed only with explicit consent\n' : ''}

---

## 5. Cookies & Tracking (ANPD Guidance + Art. 8)

- [ ] Cookie consent banner implemented before loading any trackers
- [ ] Tracker list documented (Google Analytics, Meta Pixel, Hotjar, etc.)
- [ ] Strictly necessary cookies excluded from consent (session, CSRF)
- [ ] Cookie policy page accessible at \`/politica-de-privacidade\` or \`/cookies\`
- [ ] Consent preferences stored and respected

---

## 6. Required Pages & Links

- [ ] Privacy Policy — \`/politica-de-privacidade\` (Portuguese) or \`/privacy\`
- [ ] Terms of Use — \`/termos-de-uso\` or \`/terms\`
- [ ] Cookie Policy (may be part of Privacy Policy)
- [ ] DPO / Contact e-mail visible (e.g., \`privacidade@${projectName.replace(/[^a-z0-9]/gi, '').toLowerCase()}.com.br\`)

---

## 7. Third-Party Data Processors (Art. 39 — LGPD)

Document every sub-processor:

| Processor | Purpose | Country | DPA Signed? |
|-----------|---------|---------|-------------|
| Vercel / Railway | Hosting | USA | ✅ |
| Supabase / PlanetScale | Database | USA | ✅ |
${hasPayments ? '| Stripe / Pagar.me | Payments | USA / Brazil | ✅ |\n' : ''}
| Resend / SendGrid | Transactional e-mail | USA | ✅ |

---

## 8. Data Retention & Deletion Schedule

| Data Category | Retention Period | Action on Expiry |
|--------------|-----------------|-----------------|
| User account data | Until deletion request or 3 years inactivity | Anonymise / Delete |
| Server logs | 90 days | Auto-delete |
| Financial records | 5 years (Lei nº 9.613/98) | Archive, then delete |
| Consent records | 5 years after consent withdrawal | Archive |

---

*Re-run \`npx @vibeharness/cli init\` to regenerate this checklist after updating your threat model.*
`;
}
