export interface PrdInput {
  projectName: string;
  problem: string;
  targetUsers: string;
  mainFeatures: string[];
  successMetrics: string[];
  outOfScope: string[];
}

function listOrPlaceholder(items: string[], placeholder: string): string {
  if (items.length === 0) return `- [ ] ${placeholder}`;
  return items.map((f) => `- [ ] ${f}`).join('\n');
}

export function prdTemplate(input: PrdInput): string {
  const date = new Date().toISOString().split('T')[0];

  return `# Product Requirements Document — ${input.projectName}
> Generated by vibe-harness on ${date}.
> This is a living document — keep it updated as the product evolves.

## 1. Problem Statement

${input.problem || '<!-- Describe the problem this product solves, in 2-3 sentences. -->'}

## 2. Target Users / Personas

${input.targetUsers || '<!-- Who is this for? Describe the primary persona and their context. -->'}

## 3. User Stories

<!-- Format: As a <persona>, I want <action>, so that <benefit>. -->

| # | User Story | Priority | Status |
|---|------------|----------|--------|
| 1 | As a ..., I want ..., so that ... | P0 | ⬜ |
| 2 | As a ..., I want ..., so that ... | P1 | ⬜ |

## 4. Core Features (MVP)

${listOrPlaceholder(input.mainFeatures, 'Describe feature 1')}

## 5. Success Metrics

${listOrPlaceholder(input.successMetrics, 'Define a measurable metric (e.g., activation rate ≥ 30%)')}

## 6. Out of Scope (MVP)

${listOrPlaceholder(input.outOfScope, 'Explicitly list what the MVP will NOT do')}

## 7. Non-Functional Requirements

- **Security:** no known High/Critical vulnerabilities at release (\`npx @vibeharness/cli audit\`).
- **Privacy:** LGPD/GDPR compliance per \`.vibe/LGPD_POLICY.md\` (if PII is processed).
- **Performance:** p95 response time ≤ 500 ms on critical API routes.
- **Accessibility:** WCAG 2.1 AA for all interactive UI.

## 8. Open Questions

- [ ] List unresolved decisions here.

## 9. Definition of Done

A feature is "done" when:
1. All acceptance criteria are met.
2. Unit and integration tests pass.
3. \`npx @vibeharness/cli audit\` score ≥ 70.
4. Code review approved.
5. No open security findings from \`npx @vibeharness/cli audit\`.
`;
}
