export function specTemplate(projectName: string, stack: string[]): string {
  const stackLine = stack.length ? stack.join(', ') : 'TBD';
  const date = new Date().toISOString().split('T')[0];

  return `# Project Specification — ${projectName}
> Generated by vibe-harness on ${date}
> Update this file to reflect your actual requirements.

## 1. Project Overview

**Name:** ${projectName}
**Stack:** ${stackLine}
**Created:** ${date}

## 2. Business Rules (Non-Negotiable)

<!-- List the inviolable business rules here. Examples: -->
- [ ] Describe rule 1
- [ ] Describe rule 2

## 3. Data Model

<!-- Describe your core entities and relationships. -->

### Entities
| Entity | Description |
|--------|-------------|
| User   | Platform user |

## 4. Architecture Decisions

- **API style:** REST / GraphQL / tRPC (choose one)
- **Auth provider:** (e.g., Auth.js, Supabase Auth, Clerk)
- **Database:** (e.g., PostgreSQL via Prisma, Supabase, SQLite)
- **Deployment target:** (e.g., Vercel, Railway, Fly.io, AWS)

## 5. Out of Scope (MVP)

- List features explicitly excluded from the first release.

## 6. Definition of Done

A feature is "done" when:
1. All acceptance criteria are met.
2. Unit and integration tests pass.
3. \`npx @vibeharness/cli audit\` score ≥ 70.
4. Code review approved.
5. No open security findings from \`npx @vibeharness/cli audit\`.
`;
}

export function constitutionTemplate(projectName: string): string {
  return `# Constitution — ${projectName}
> Non-negotiable architectural and security laws for this project.
> Generated by vibe-harness. Discuss with the team before changing.

## Law 1 — Security First
No feature ships with a known High or Critical security vulnerability.

## Law 2 — Secrets Stay Out of Code
Credentials, API keys, and tokens live exclusively in environment variables
managed by the deployment platform or a secrets manager. Violations block CI.

## Law 3 — Input Validation is Mandatory
Every external input (HTTP body, query params, file uploads, env vars at boot)
must be validated with a typed schema before use.

## Law 4 — Migrations, Not Magic
Database schema changes must be captured as versioned, reversible migration files.
Running \`db push\` or raw DDL in production is forbidden.

## Law 5 — Test Coverage for Critical Paths
Authentication, payment, and data-deletion flows must have integration tests
with ≥ 80 % branch coverage before merging to main.

## Law 6 — Dependency Hygiene
No new dependency may be added without:
a) A stated reason in the PR description.
b) A CVE check (\`npm audit\` / \`pip-audit\`).
c) Confirmation that an existing package cannot fulfil the need.

## Law 7 — Accessibility is Not Optional
Interactive UI elements (buttons, forms, dialogs) must have accessible labels,
keyboard navigation, and meet WCAG 2.1 AA colour-contrast ratios.
`;
}
