import type { Catalog, CatalogEntry } from '../registry/index.js';
import { topEntries, isLicenseAllowed } from '../registry/index.js';

export interface StackPlanInput {
  projectName: string;
  projectType: 'fullstack-web' | 'api' | 'landing' | 'saas';
  catalog: Catalog;
  catalogStale: boolean;
  threatModel: { hasPayments: boolean; hasAuth: boolean; hasSensitiveData: boolean } | null;
  detectedStack: string[];
}

function entryLine(entry: CatalogEntry, primary: boolean, licenseAllowed: boolean): string {
  const licenseFlag = entry.licenseNote
    ? ` — ⚠️ ${entry.licenseNote}`
    : !licenseAllowed
      ? ' — ⚠️ license needs review'
      : '';
  const tag = primary ? '**→ primary**' : 'alternative';
  const notes = entry.notes ? ` — ${entry.notes}` : '';
  return `- [${tag}] [${entry.name}](https://github.com/${entry.repo}) (⭐ ${entry.stars.toLocaleString('en-US')}, ${entry.license})${notes}${licenseFlag}`;
}

function categorySection(
  catalog: Catalog,
  title: string,
  category: string,
  why: string
): string {
  const top = topEntries(catalog, category, 3);
  if (top.length === 0) return '';
  const lines = [`### ${title}`, '', `_${why}_`, ''];
  top.forEach((entry, i) => {
    lines.push(entryLine(entry, i === 0, isLicenseAllowed(catalog, entry)));
  });
  return lines.join('\n') + '\n';
}

export function stackPlanTemplate(input: StackPlanInput): string {
  const { projectName, projectType, catalog, catalogStale, threatModel, detectedStack } = input;
  const date = new Date().toISOString().split('T')[0];

  const hasAuth = threatModel?.hasAuth ?? true;
  const hasPayments = threatModel?.hasPayments ?? false;
  const hasSensitiveData = threatModel?.hasSensitiveData ?? false;

  const sections: string[] = [];

  sections.push(`# Stack Recommendation — ${projectName}
> Generated by vibe-harness on ${date} from the curated registry (last sync: ${catalog.lastSync}).
> Project type: **${projectType}** · Detected stack: ${detectedStack.length ? detectedStack.join(', ') : 'none'}
${catalogStale ? '> ⚠️ **Registry is stale (> 30 days).** Run the registry sync before relying on these numbers.\n' : ''}`);

  if (projectType === 'landing') {
    sections.push(categorySection(catalog, 'Frontend', 'frontend', 'Content-first sites favour static/islands frameworks.'));
  } else if (projectType === 'api') {
    sections.push(categorySection(catalog, 'Backend', 'backend', 'API-only project — pick the HTTP layer first.'));
  } else {
    sections.push(categorySection(catalog, 'Frontend', 'frontend', 'Primary UI layer.'));
    sections.push(categorySection(catalog, 'Backend', 'backend', 'Skip if the frontend framework already covers server logic (e.g., Next.js server actions).'));
  }

  sections.push(categorySection(catalog, 'Database', 'database', 'Persistence layer; always use versioned migrations.'));
  sections.push(categorySection(catalog, 'Validation', 'validation', 'Schema validation is mandatory on every external input (Constitution Law 3).'));

  if (hasAuth) {
    sections.push(categorySection(catalog, 'Authentication', 'auth', 'Project has authentication (threat model).'));
  }
  if (hasPayments) {
    sections.push(categorySection(catalog, 'Payments', 'payments', 'Project handles payments (threat model).'));
  }

  sections.push(categorySection(catalog, 'Testing', 'testing', 'Critical paths require tests before merge (Constitution Law 5).'));

  if (projectType !== 'landing') {
    sections.push(categorySection(catalog, 'Deployment / Hosting', 'deploy', 'Prefer platforms with preview environments and secret management.'));
  }

  sections.push(categorySection(catalog, 'MCP Servers', 'mcp', 'Extend your AI agent with tool access.'));
  sections.push(categorySection(catalog, 'AI-Assisted Development Tools', 'ai-tools', 'Methodology and workflow references, ranked by community adoption.'));
  sections.push(categorySection(catalog, 'Security Tooling', 'security', 'Run secret scanning and CVE scanning in CI.'));
  sections.push(categorySection(catalog, 'Dependency Maintenance', 'maintenance', 'Keep the stack fresh — run `vibe-harness doctor` regularly.'));

  const privacyNote = hasSensitiveData
    ? `- **Privacy:** project processes PII — follow \`.vibe/LGPD_POLICY.md\`, enable RLS, encrypt at rest.`
    : '- **Privacy:** no PII declared — re-run `vibe-harness init` if that changes.';

  sections.push(`## Next Steps

1. Confirm or adjust each primary choice above, then copy decisions into \`.vibe/SPEC.md\` (section 4).
2. Run \`vibe-harness prd\` if the PRD is not written yet.
3. Run \`vibe-harness doctor --fix\` to install Dependabot and keep dependencies fresh.
4. Before shipping: \`vibe-harness audit --report\` (target ≥ 70).

## Guardrails

- **Security:** never commit secrets; parameterised SQL only; validate all inputs.
${privacyNote}
- **Freshness:** re-run \`vibe-harness plan\` after each registry sync to revisit recommendations.
`);

  return sections.filter(Boolean).join('\n---\n\n');
}
