/**
 * Apply recipes — what VibeHarness actually DOES for each curated registry entry.
 * Keyed by catalog `repo`. Entries without a recipe degrade gracefully to a
 * recommendation (the plan still lists them; apply skips with a reason).
 *
 * Invariant enforced by core/apply.ts: recipe files may only be root-level
 * configs or live under .vibe/ — never inside the user's src/.
 */

export interface EnvVarSpec {
  name: string;
  hint: string;
}

export interface RecipeFile {
  /** Path relative to the project root. Must be a root config or under .vibe/. */
  path: string;
  content: string;
}

export interface BinarySpec {
  /** Binary name to check on PATH. */
  name: string;
  /** Formula name for Homebrew (macOS/Linuxbrew). */
  brew?: string;
  notes: string;
}

export interface ApplyRecipe {
  install?: string[];
  devInstall?: string[];
  envVars?: EnvVarSpec[];
  files?: RecipeFile[];
  binary?: BinarySpec;
  note?: string;
  /**
   * Human/AI-readable steps to integrate the generated starters into the
   * app. Surfaced in .vibe/starters/README.md, the ActionResult and MCP
   * tools so an AI agent can perform the wiring with user consent.
   */
  wiring?: string[];
}

const ZOD_STARTER = `// Starter generated by VibeHarness — copy into your API layer and adapt.
// Constitution Law 3: every external input MUST be validated with a schema.
import { z } from 'zod';

export const createUserSchema = z.object({
  body: z.object({
    name: z.string().min(1).max(200),
    email: z.string().email(),
    password: z.string().min(12),
  }),
});

// Express example — reject anything that does not parse:
//   const parsed = createUserSchema.safeParse(req);
//   if (!parsed.success) return res.status(400).json({ error: parsed.error.flatten() });
`;

const VALIBOT_STARTER = `// Starter generated by VibeHarness — copy into your API layer and adapt.
// Constitution Law 3: every external input MUST be validated with a schema.
import * as v from 'valibot';

export const createUserSchema = v.object({
  body: v.object({
    name: v.pipe(v.string(), v.minLength(1), v.maxLength(200)),
    email: v.pipe(v.string(), v.email()),
    password: v.pipe(v.string(), v.minLength(12)),
  }),
});

// Usage: const parsed = v.safeParse(createUserSchema, req);
`;

const YUP_STARTER = `// Starter generated by VibeHarness — copy into your API layer and adapt.
// Constitution Law 3: every external input MUST be validated with a schema.
import * as yup from 'yup';

export const createUserSchema = yup.object({
  body: yup.object({
    name: yup.string().min(1).max(200).required(),
    email: yup.string().email().required(),
    password: yup.string().min(12).required(),
  }),
});

// Usage: try { await createUserSchema.validate(req, { strict: true }); } catch (e) { /* 400 */ }
`;

const VITEST_CONFIG = `import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    include: ['tests/**/*.test.ts', 'src/**/*.test.ts'],
    coverage: { reporter: ['text', 'html'] },
  },
});
`;

const ESLINT_CONFIG = `// Flat config generated by VibeHarness — Constitution Law 6 (dependency
// hygiene) starts with a linter that catches insecure patterns early.
// TypeScript project? Add typescript-eslint:
//   npm i -D typescript-eslint  →  import tseslint from 'typescript-eslint';
//   then spread ...tseslint.configs.recommended into the array below.
import js from '@eslint/js';
import globals from 'globals';

export default [
  { ignores: ['dist/', 'node_modules/', 'coverage/', 'build/'] },
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.node },
    },
    rules: {
      'no-eval': 'error',
      'no-implied-eval': 'error',
    },
  },
];
`;

const PRETTIER_CONFIG = `{
  "singleQuote": true,
  "printWidth": 100,
  "trailingComma": "es5"
}
`;

const PRETTIER_IGNORE = `dist
node_modules
coverage
build
package-lock.json
`;

const VITEST_STARTER = `// Starter generated by VibeHarness — move to tests/ and adapt.
import { describe, it, expect } from 'vitest';

describe('example', () => {
  it('works', () => {
    expect(1 + 1).toBe(2);
  });
});
`;

const PLAYWRIGHT_CONFIG_STARTER = `// Starter generated by VibeHarness — review, then copy to playwright.config.ts at the root.
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  use: { baseURL: process.env.E2E_BASE_URL ?? 'http://localhost:3000' },
  // Point webServer.command at your real dev server before running E2E.
  // It is executed via shell by Playwright — keep it a literal you control,
  // never an environment variable or user input.
  // webServer: { command: 'npm run dev', url: 'http://localhost:3000' },
});
`;

const SUPABASE_STARTER = `// Starter generated by VibeHarness — copy into your lib/ layer and adapt.
import { createClient } from '@supabase/supabase-js';

const url = process.env.SUPABASE_URL;
const anonKey = process.env.SUPABASE_ANON_KEY;
if (!url || !anonKey) throw new Error('Missing SUPABASE_URL / SUPABASE_ANON_KEY');

export const supabase = createClient(url, anonKey);

// LGPD/SECURITY: enable Row-Level Security on EVERY table before shipping.
// Never use the service-role key in client-side code.
`;

const PRISMA_SCHEMA_STARTER = `// Starter generated by VibeHarness — review, then move to prisma/schema.prisma
// (run \`npx prisma migrate dev\` to create the first versioned migration).
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id           String   @id @default(cuid())
  email        String   @unique
  passwordHash String
  createdAt    DateTime @default(now())
}
`;

const DRIZZLE_CONFIG = `import { defineConfig } from 'drizzle-kit';

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) throw new Error('Missing DATABASE_URL — set it in .env (see .env.example)');

export default defineConfig({
  schema: './db/schema.ts',
  out: './db/migrations',
  dialect: 'postgresql',
  dbCredentials: { url: databaseUrl },
});
`;

const DRIZZLE_STARTER = `// Starter generated by VibeHarness — copy to db/schema.ts and adapt.
// Versioned migrations only: \`npx drizzle-kit generate\` then \`npx drizzle-kit migrate\`.
import { pgTable, text, timestamp } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: text('id').primaryKey(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});
`;

const PRISMA_CLIENT_STARTER = `// Starter generated by VibeHarness — copy to src/lib/prisma.ts.
// SERVERLESS-SAFE SINGLETON: serverless platforms (Vercel/Netlify/Lambda)
// reuse warm containers — instantiating PrismaClient per request exhausts
// the database connection pool (Postgres caps at ~100). The globalThis
// cache keeps ONE client per container across hot reloads and invocations.
import { PrismaClient } from '@prisma/client';

const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    // POOLING: on serverless + Neon/Supabase, add pgbouncer=true to the
    // DATABASE_URL query string, or use \`prisma accelerate\` (port 6543,
    // pooled). Direct connections (5432) should be reserved for migrations.
    // Example: postgresql://USER:PASSWORD@your-db-host:5432/db?pgbouncer=true&connection_limit=1
  });

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;
`;

const DRIZZLE_CLIENT_STARTER = `// Starter generated by VibeHarness — copy to db/client.ts.
// SERVERLESS-SAFE SINGLETON: same rationale as the Prisma starter — one
// connection (or pool) per warm container, never per request.
import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import * as schema from './schema';

const globalForDb = globalThis as unknown as { pool?: Pool };

export const pool =
  globalForDb.pool ??
  new Pool({
    connectionString: process.env.DATABASE_URL,
    // POOLING: on serverless keep max SMALL (1-3) per container — every warm
    // instance holds its own pool, and Postgres caps total connections.
    // Neon/Supabase pooled endpoints (port 6543) are the safer default.
    max: process.env.NODE_ENV === 'production' ? 3 : 10,
  });

if (process.env.NODE_ENV !== 'production') globalForDb.pool = pool;

export const db = drizzle(pool, { schema });
`;

const MIGRATIONS_GUIDE = `# Migrations — troubleshooting for vibecoders

Versioned migrations are your database's git history. This guide unblocks
the three failures you WILL hit. Golden rule: **never edit an applied
migration** — always add a new one.

## 1. "Migration failed to apply" (drizzle/prisma migrate deploy in CI)

A migration that half-applied leaves the DB out of sync.

- Prisma: \`npx prisma migrate status\` shows which one failed, then either
  fix the data issue and re-run, or mark it resolved:
  \`npx prisma migrate resolve --rolled-back <migration_name>\`.
- Drizzle: the journal (\`db/migrations/meta/_journal.json\`) tracks applied
  steps — compare with the \`drizzle.__drizzle_migrations\` table.

## 2. "Drift" — schema.prisma/schema.ts diverged from migrations

You edited the schema and the DB directly (or used db push once).

- Regenerate the diff as a NEW migration: \`npx prisma migrate dev --name sync\`
  (dev DB only!) or \`npx drizzle-kit generate\`. Commit the generated files.
- NEVER run \`db push\` against staging/prod — it applies changes without
  history, which is exactly what the audit blocks.

## 3. "P3005 / database is not empty" (Prisma first migration on existing DB)

\`npx prisma migrate dev --baseline\` marks the existing schema as the
starting point, then future changes become normal incremental migrations.

## Serverless: migrations do NOT run in your app

Lambdas are read-only-ish and short-lived — run migrations in CI
(\`prisma migrate deploy\` / \`drizzle-kit migrate\`) as a deploy step, using a
DIRECT (non-pooled) connection string. The runtime app uses the pooled URL.
`;

const BETTER_AUTH_STARTER = `// Starter generated by VibeHarness — copy into your auth layer and adapt.
import { betterAuth } from 'better-auth';

export const auth = betterAuth({
  emailAndPassword: { enabled: true },
  // SECURITY: session cookies must be httpOnly + secure + sameSite.
  // SECURITY: never log tokens or PII; hash passwords with bcrypt/argon2.
});
`;

const NEXT_AUTH_STARTER = `// Starter generated by VibeHarness — copy into your auth route and adapt.
// SECURITY: AUTH_SECRET must be a strong random value, never committed.
import NextAuth from 'next-auth';

export const { handlers, auth, signIn, signOut } = NextAuth({
  providers: [],
  session: { strategy: 'database' },
});
`;

const STRIPE_STARTER = `// Starter generated by VibeHarness — copy into your webhook route and adapt.
import Stripe from 'stripe';

const secretKey = process.env.STRIPE_SECRET_KEY;
if (!secretKey) throw new Error('Missing STRIPE_SECRET_KEY — set it in .env (see .env.example)');
const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET;
if (!webhookSecret) throw new Error('Missing STRIPE_WEBHOOK_SECRET — set it in .env (see .env.example)');

const stripe = new Stripe(secretKey);

// SECURITY: ALWAYS verify webhook signatures — never trust the raw payload.
export async function handleWebhook(req: Request, rawBody: string): Promise<Response> {
  const signature = req.headers.get('stripe-signature');
  if (!signature) return new Response('Missing signature', { status: 400 });
  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(rawBody, signature, webhookSecret);
  } catch {
    // Invalid signature — return a generic 400; never leak verification
    // internals or stack traces to the caller.
    return new Response('Invalid signature', { status: 400 });
  }
  // Handle event.type here; use idempotency keys for any charge/refund.
  return new Response('ok');
}
`;

// Curated MCP servers. Versions are PINNED (supply-chain hardening):
// `npx -y <pkg>` without a version auto-executes whatever latest resolves to,
// turning a registry compromise into code execution inside the AI client.
// Verified on the npm registry 2026-08-16; `server-fetch` was REMOVED — the
// package no longer exists on npm and an unpinned reference would be
// typosquat bait. Update deliberately via scripts/registry-sync.
const MCP_SERVER_FILESYSTEM = '@modelcontextprotocol/server-filesystem@2026.7.10';
const MCP_SERVER_MEMORY = '@modelcontextprotocol/server-memory@2026.7.4';

export const APPLY_RECIPES: Record<string, ApplyRecipe> = {
  // ---- Validation -------------------------------------------------------
  'colinhacks/zod': {
    install: ['zod'],
    files: [{ path: '.vibe/starters/validation/schema-example.ts', content: ZOD_STARTER }],
    wiring: [
      'Copy .vibe/starters/validation/schema-example.ts into your API layer (e.g. src/schemas/) and adapt fields.',
      'Validate every req.body with schema.safeParse — return 400 with the flattened error on failure.',
    ],
    note: 'Default schema validation for TypeScript APIs (Constitution Law 3).',
  },
  'fabian-hiller/valibot': {
    install: ['valibot'],
    files: [{ path: '.vibe/starters/validation/schema-example.ts', content: VALIBOT_STARTER }],
    wiring: [
      'Copy .vibe/starters/validation/schema-example.ts into your API layer (e.g. src/schemas/) and adapt fields.',
      'Validate every req.body with v.safeParse — return 400 with the issues on failure.',
    ],
    note: 'Smaller-bundle schema validation.',
  },
  'jquense/yup': {
    install: ['yup'],
    files: [{ path: '.vibe/starters/validation/schema-example.ts', content: YUP_STARTER }],
    wiring: [
      'Copy .vibe/starters/validation/schema-example.ts into your API layer (e.g. src/schemas/) and adapt fields.',
      'Validate every req.body with schema.validate({ strict: true }) — return 400 on throw.',
    ],
    note: 'Mature schema validation, common in form ecosystems.',
  },

  // ---- Linting & formatting ----------------------------------------------
  'eslint/eslint': {
    devInstall: ['eslint', '@eslint/js', 'globals'],
    files: [{ path: 'eslint.config.mjs', content: ESLINT_CONFIG }],
    wiring: [
      'Add "lint": "eslint ." to package.json scripts and run it before every merge.',
      'TypeScript project: `npm i -D typescript-eslint` and add `...tseslint.configs.recommended` to eslint.config.mjs (instructions inside the file).',
    ],
    note: 'Linter first — dead code and insecure patterns surface here, before the audit does (Constitution Law 6).',
  },
  'prettier/prettier': {
    devInstall: ['prettier'],
    files: [
      { path: '.prettierrc.json', content: PRETTIER_CONFIG },
      { path: '.prettierignore', content: PRETTIER_IGNORE },
    ],
    wiring: [
      'Add "format": "prettier --write ." and "format:check": "prettier --check ." to package.json scripts.',
      'Run format:check in CI so style drift never merges.',
    ],
    note: 'Formatter — ends style debates; complements ESLint without overlapping it.',
  },

  // ---- Testing ----------------------------------------------------------
  'vitest-dev/vitest': {
    devInstall: ['vitest'],
    files: [
      { path: 'vitest.config.ts', content: VITEST_CONFIG },
      { path: '.vibe/starters/testing/example.test.ts', content: VITEST_STARTER },
    ],
    wiring: [
      'Move .vibe/starters/testing/example.test.ts to tests/example.test.ts and add real cases.',
      'Add "test": "vitest run" to package.json scripts.',
    ],
    note: 'Unit tests — critical routes need tests before merge (Constitution Law 5).',
  },
  'jestjs/jest': {
    devInstall: ['jest'],
    note: 'Add a jest.config matching your TS setup; keep tests in tests/.',
  },
  'microsoft/playwright': {
    devInstall: ['@playwright/test'],
    files: [{ path: '.vibe/starters/testing/playwright.config.ts', content: PLAYWRIGHT_CONFIG_STARTER }],
    wiring: [
      'Copy .vibe/starters/testing/playwright.config.ts to playwright.config.ts at the project root.',
      'Create e2e/ with your first spec, then run `npx playwright install` for browsers.',
    ],
    note: 'Run `npx playwright install` to download browsers when you are ready for E2E.',
  },

  // ---- Database ---------------------------------------------------------
  'supabase/supabase': {
    install: ['@supabase/supabase-js'],
    envVars: [
      { name: 'SUPABASE_URL', hint: 'Project URL from the Supabase dashboard' },
      { name: 'SUPABASE_ANON_KEY', hint: 'Public anon key (never the service-role key in clients)' },
    ],
    files: [{ path: '.vibe/starters/database/supabase-client.ts', content: SUPABASE_STARTER }],
    wiring: [
      'Copy .vibe/starters/database/supabase-client.ts into src/lib/supabase.ts (server-side only).',
      'Set SUPABASE_URL and SUPABASE_ANON_KEY in .env (values from the Supabase dashboard).',
      'Enable Row-Level Security on every table via the Supabase dashboard before shipping.',
    ],
    note: 'Enable Row-Level Security on every table before shipping (LGPD/security).',
  },
  'prisma/prisma': {
    install: ['@prisma/client'],
    devInstall: ['prisma'],
    envVars: [{ name: 'DATABASE_URL', hint: 'Postgres connection string — never commit the real value' }],
    files: [
      { path: '.vibe/starters/database/schema.prisma', content: PRISMA_SCHEMA_STARTER },
      { path: '.vibe/starters/database/prisma-client.ts', content: PRISMA_CLIENT_STARTER },
      { path: '.vibe/starters/database/MIGRATIONS.md', content: MIGRATIONS_GUIDE },
    ],
    wiring: [
      'Move .vibe/starters/database/schema.prisma to prisma/schema.prisma.',
      'Copy .vibe/starters/database/prisma-client.ts to src/lib/prisma.ts — import { prisma } everywhere (singleton prevents pool exhaustion on serverless).',
      'Set DATABASE_URL in .env, then run `npx prisma migrate dev --name init` (versioned migrations only).',
      'Deploying to serverless? Add pgbouncer=true to DATABASE_URL (or use Prisma Accelerate) — see the comment in prisma-client.ts.',
      'Migration failed or out of sync? Read .vibe/starters/database/MIGRATIONS.md before improvising.',
    ],
    note: 'Move the starter schema to prisma/schema.prisma; versioned migrations only.',
  },
  'drizzle-team/drizzle-orm': {
    install: ['drizzle-orm'],
    devInstall: ['drizzle-kit'],
    envVars: [{ name: 'DATABASE_URL', hint: 'Postgres connection string — never commit the real value' }],
    files: [
      { path: 'drizzle.config.ts', content: DRIZZLE_CONFIG },
      { path: '.vibe/starters/database/schema.ts', content: DRIZZLE_STARTER },
      { path: '.vibe/starters/database/client.ts', content: DRIZZLE_CLIENT_STARTER },
      { path: '.vibe/starters/database/MIGRATIONS.md', content: MIGRATIONS_GUIDE },
    ],
    wiring: [
      'Copy .vibe/starters/database/schema.ts to db/schema.ts and define your tables.',
      'Copy .vibe/starters/database/client.ts to db/client.ts — import { db } everywhere (pooled singleton prevents pool exhaustion on serverless).',
      'Run `npx drizzle-kit generate` then `npx drizzle-kit migrate` (versioned migrations only).',
      'Deploying to serverless? Use the Neon/Supabase pooled endpoint (port 6543) for the app and a DIRECT connection for migrations — see client.ts comments.',
      'Migration failed or out of sync? Read .vibe/starters/database/MIGRATIONS.md before improvising.',
    ],
    note: 'Versioned migrations only: drizzle-kit generate + migrate.',
  },

  // ---- Auth -------------------------------------------------------------
  'better-auth/better-auth': {
    install: ['better-auth'],
    envVars: [{ name: 'BETTER_AUTH_SECRET', hint: 'Strong random secret (openssl rand -hex 32)' }],
    files: [{ path: '.vibe/starters/auth/auth-setup.ts', content: BETTER_AUTH_STARTER }],
    wiring: [
      'Copy .vibe/starters/auth/auth-setup.ts into src/lib/auth.ts and configure providers.',
      'Set BETTER_AUTH_SECRET in .env (openssl rand -hex 32).',
      'Protect routes with the session helper; cookies must stay httpOnly + secure + sameSite.',
    ],
    note: 'Session cookies: httpOnly + secure + sameSite; never log tokens.',
  },
  'nextauthjs/next-auth': {
    install: ['next-auth'],
    envVars: [
      { name: 'AUTH_SECRET', hint: 'Strong random secret (openssl rand -hex 32)' },
      { name: 'NEXTAUTH_URL', hint: 'Canonical URL of the app (e.g. https://app.example.com)' },
    ],
    files: [{ path: '.vibe/starters/auth/auth-setup.ts', content: NEXT_AUTH_STARTER }],
    wiring: [
      'Copy .vibe/starters/auth/auth-setup.ts to src/auth.ts and add your providers.',
      'Create the catch-all route app/api/auth/[...nextauth]/ts exporting { handlers as GET, POST }.',
      'Set AUTH_SECRET and NEXTAUTH_URL in .env.',
    ],
    note: 'Prefer database sessions; rotate AUTH_SECRET on any suspected leak.',
  },

  // ---- Payments ---------------------------------------------------------
  'stripe/stripe-node': {
    install: ['stripe'],
    envVars: [
      { name: 'STRIPE_SECRET_KEY', hint: 'sk_live_… in production, sk_test_… in development' },
      { name: 'STRIPE_WEBHOOK_SECRET', hint: 'whsec_… from the Stripe webhook endpoint' },
    ],
    files: [{ path: '.vibe/starters/payments/stripe-webhook.ts', content: STRIPE_STARTER }],
    wiring: [
      'Copy .vibe/starters/payments/stripe-webhook.ts into your webhook route (e.g. app/api/webhooks/stripe/route.ts).',
      'Set STRIPE_SECRET_KEY and STRIPE_WEBHOOK_SECRET in .env; always verify the signature.',
      'Handle event types idempotently (use event.id as the idempotency key).',
    ],
    note: 'Always verify webhook signatures; use idempotency keys on charges.',
  },

  // ---- Security (binary tools — installed only with explicit consent) ---
  'gitleaks/gitleaks': {
    binary: {
      name: 'gitleaks',
      brew: 'gitleaks',
      notes: 'Full 150+ rule secret detection for the pre-commit hook (fallback patterns already installed).',
    },
  },
  'google/osv-scanner': {
    binary: {
      name: 'osv-scanner',
      brew: 'osv-scanner',
      notes: 'Multi-ecosystem CVE scanning via OSV.dev (complements npm audit).',
    },
  },

  // ---- MCP --------------------------------------------------------------
  'modelcontextprotocol/servers': {
    files: [
      {
        // Strict, comment-free JSON: `.mcp.json` is parsed by clients that
        // reject `//` comments (Claude Code among them).
        path: '.mcp.json',
        content: `{
  "mcpServers": {
    "filesystem": {
      "command": "npx",
      "args": ["-y", "${MCP_SERVER_FILESYSTEM}", "."]
    },
    "memory": {
      "command": "npx",
      "args": ["-y", "${MCP_SERVER_MEMORY}"]
    }
  }
}
`,
      },
      {
        path: '.vibe/starters/mcp/cursor-mcp.json',
        content: `{
  "mcpServers": {
    "filesystem": {
      "command": "npx",
      "args": ["-y", "${MCP_SERVER_FILESYSTEM}", "."]
    },
    "memory": {
      "command": "npx",
      "args": ["-y", "${MCP_SERVER_MEMORY}"]
    }
  }
}
`,
      },
    ],
    wiring: [
      'Review each MCP server before trusting it (https://modelcontextprotocol.io); the filesystem server gets read/write access to the project directory.',
      'Cursor users: merge .vibe/starters/mcp/cursor-mcp.json into Settings → MCP → Add new global MCP server.',
    ],
    note: 'Curated MCP servers configured for your agent — versions pinned, review each server before trusting it.',
  },

  // ---- Deploy (accounts live outside the repo — config guidance only) ---
  'coollabsio/coolify': {
    envVars: [
      { name: 'COOLIFY_URL', hint: 'Your Coolify instance URL (self-hosted PaaS)' },
      { name: 'COOLIFY_API_TOKEN', hint: 'API token from Coolify — treat as a secret' },
    ],
    note: 'Deployment target — connect the repo in the Coolify dashboard; no code changes needed.',
  },
};
