/**
 * Apply recipes — what VibeHarness actually DOES for each curated registry entry.
 * Keyed by catalog `repo`. Entries without a recipe degrade gracefully to a
 * recommendation (the plan still lists them; apply skips with a reason).
 *
 * Invariant enforced by core/apply.ts: recipe files may only be root-level
 * configs or live under .vibe/ — never inside the user's src/.
 */

export interface EnvVarSpec {
  name: string;
  hint: string;
}

export interface RecipeFile {
  /** Path relative to the project root. Must be a root config or under .vibe/. */
  path: string;
  content: string;
}

export interface BinarySpec {
  /** Binary name to check on PATH. */
  name: string;
  /** Formula name for Homebrew (macOS/Linuxbrew). */
  brew?: string;
  notes: string;
}

export interface ApplyRecipe {
  install?: string[];
  devInstall?: string[];
  envVars?: EnvVarSpec[];
  files?: RecipeFile[];
  binary?: BinarySpec;
  note?: string;
}

const ZOD_STARTER = `// Starter generated by VibeHarness — copy into your API layer and adapt.
// Constitution Law 3: every external input MUST be validated with a schema.
import { z } from 'zod';

export const createUserSchema = z.object({
  body: z.object({
    name: z.string().min(1).max(200),
    email: z.string().email(),
    password: z.string().min(12),
  }),
});

// Express example — reject anything that does not parse:
//   const parsed = createUserSchema.safeParse(req);
//   if (!parsed.success) return res.status(400).json({ error: parsed.error.flatten() });
`;

const VALIBOT_STARTER = `// Starter generated by VibeHarness — copy into your API layer and adapt.
// Constitution Law 3: every external input MUST be validated with a schema.
import * as v from 'valibot';

export const createUserSchema = v.object({
  body: v.object({
    name: v.pipe(v.string(), v.minLength(1), v.maxLength(200)),
    email: v.pipe(v.string(), v.email()),
    password: v.pipe(v.string(), v.minLength(12)),
  }),
});

// Usage: const parsed = v.safeParse(createUserSchema, req);
`;

const YUP_STARTER = `// Starter generated by VibeHarness — copy into your API layer and adapt.
// Constitution Law 3: every external input MUST be validated with a schema.
import * as yup from 'yup';

export const createUserSchema = yup.object({
  body: yup.object({
    name: yup.string().min(1).max(200).required(),
    email: yup.string().email().required(),
    password: yup.string().min(12).required(),
  }),
});

// Usage: try { await createUserSchema.validate(req, { strict: true }); } catch (e) { /* 400 */ }
`;

const VITEST_CONFIG = `import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    include: ['tests/**/*.test.ts', 'src/**/*.test.ts'],
    coverage: { reporter: ['text', 'html'] },
  },
});
`;

const VITEST_STARTER = `// Starter generated by VibeHarness — move to tests/ and adapt.
import { describe, it, expect } from 'vitest';

describe('example', () => {
  it('works', () => {
    expect(1 + 1).toBe(2);
  });
});
`;

const PLAYWRIGHT_CONFIG_STARTER = `// Starter generated by VibeHarness — review, then copy to playwright.config.ts at the root.
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  use: { baseURL: process.env.E2E_BASE_URL ?? 'http://localhost:3000' },
  webServer: process.env.E2E_COMMAND
    ? { command: process.env.E2E_COMMAND, url: process.env.E2E_BASE_URL ?? 'http://localhost:3000' }
    : undefined,
});
`;

const SUPABASE_STARTER = `// Starter generated by VibeHarness — copy into your lib/ layer and adapt.
import { createClient } from '@supabase/supabase-js';

const url = process.env.SUPABASE_URL;
const anonKey = process.env.SUPABASE_ANON_KEY;
if (!url || !anonKey) throw new Error('Missing SUPABASE_URL / SUPABASE_ANON_KEY');

export const supabase = createClient(url, anonKey);

// LGPD/SECURITY: enable Row-Level Security on EVERY table before shipping.
// Never use the service-role key in client-side code.
`;

const PRISMA_SCHEMA_STARTER = `// Starter generated by VibeHarness — review, then move to prisma/schema.prisma
// (run \`npx prisma migrate dev\` to create the first versioned migration).
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id           String   @id @default(cuid())
  email        String   @unique
  passwordHash String
  createdAt    DateTime @default(now())
}
`;

const DRIZZLE_CONFIG = `import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  schema: './db/schema.ts',
  out: './db/migrations',
  dialect: 'postgresql',
  dbCredentials: { url: process.env.DATABASE_URL! },
});
`;

const DRIZZLE_STARTER = `// Starter generated by VibeHarness — copy to db/schema.ts and adapt.
// Versioned migrations only: \`npx drizzle-kit generate\` then \`npx drizzle-kit migrate\`.
import { pgTable, text, timestamp } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: text('id').primaryKey(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});
`;

const BETTER_AUTH_STARTER = `// Starter generated by VibeHarness — copy into your auth layer and adapt.
import { betterAuth } from 'better-auth';

export const auth = betterAuth({
  emailAndPassword: { enabled: true },
  // SECURITY: session cookies must be httpOnly + secure + sameSite.
  // SECURITY: never log tokens or PII; hash passwords with bcrypt/argon2.
});
`;

const NEXT_AUTH_STARTER = `// Starter generated by VibeHarness — copy into your auth route and adapt.
// SECURITY: AUTH_SECRET must be a strong random value, never committed.
import NextAuth from 'next-auth';

export const { handlers, auth, signIn, signOut } = NextAuth({
  providers: [],
  session: { strategy: 'database' },
});
`;

const STRIPE_STARTER = `// Starter generated by VibeHarness — copy into your webhook route and adapt.
import Stripe from 'stripe';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!);

// SECURITY: ALWAYS verify webhook signatures — never trust the raw payload.
export async function handleWebhook(req: Request, rawBody: string): Promise<Response> {
  const signature = req.headers.get('stripe-signature');
  if (!signature) return new Response('Missing signature', { status: 400 });
  const event = stripe.webhooks.constructEvent(
    rawBody,
    signature,
    process.env.STRIPE_WEBHOOK_SECRET!
  );
  // Handle event.type here; use idempotency keys for any charge/refund.
  return new Response('ok');
}
`;

const MCP_CONFIG_NOTE = `// .mcp.json generated by VibeHarness — curated MCP servers for your AI agent.
// Docs: https://modelcontextprotocol.io — review every server before trusting it.
`;

export const APPLY_RECIPES: Record<string, ApplyRecipe> = {
  // ---- Validation -------------------------------------------------------
  'colinhacks/zod': {
    install: ['zod'],
    files: [{ path: '.vibe/starters/validation/schema-example.ts', content: ZOD_STARTER }],
    note: 'Default schema validation for TypeScript APIs (Constitution Law 3).',
  },
  'fabian-hiller/valibot': {
    install: ['valibot'],
    files: [{ path: '.vibe/starters/validation/schema-example.ts', content: VALIBOT_STARTER }],
    note: 'Smaller-bundle schema validation.',
  },
  'jquense/yup': {
    install: ['yup'],
    files: [{ path: '.vibe/starters/validation/schema-example.ts', content: YUP_STARTER }],
    note: 'Mature schema validation, common in form ecosystems.',
  },

  // ---- Testing ----------------------------------------------------------
  'vitest-dev/vitest': {
    devInstall: ['vitest'],
    files: [
      { path: 'vitest.config.ts', content: VITEST_CONFIG },
      { path: '.vibe/starters/testing/example.test.ts', content: VITEST_STARTER },
    ],
    note: 'Unit tests — critical routes need tests before merge (Constitution Law 5).',
  },
  'jestjs/jest': {
    devInstall: ['jest'],
    note: 'Add a jest.config matching your TS setup; keep tests in tests/.',
  },
  'microsoft/playwright': {
    devInstall: ['@playwright/test'],
    files: [{ path: '.vibe/starters/testing/playwright.config.ts', content: PLAYWRIGHT_CONFIG_STARTER }],
    note: 'Run `npx playwright install` to download browsers when you are ready for E2E.',
  },

  // ---- Database ---------------------------------------------------------
  'supabase/supabase': {
    install: ['@supabase/supabase-js'],
    envVars: [
      { name: 'SUPABASE_URL', hint: 'Project URL from the Supabase dashboard' },
      { name: 'SUPABASE_ANON_KEY', hint: 'Public anon key (never the service-role key in clients)' },
    ],
    files: [{ path: '.vibe/starters/database/supabase-client.ts', content: SUPABASE_STARTER }],
    note: 'Enable Row-Level Security on every table before shipping (LGPD/security).',
  },
  'prisma/prisma': {
    install: ['@prisma/client'],
    devInstall: ['prisma'],
    envVars: [{ name: 'DATABASE_URL', hint: 'Postgres connection string — never commit the real value' }],
    files: [{ path: '.vibe/starters/database/schema.prisma', content: PRISMA_SCHEMA_STARTER }],
    note: 'Move the starter schema to prisma/schema.prisma; versioned migrations only.',
  },
  'drizzle-team/drizzle-orm': {
    install: ['drizzle-orm'],
    devInstall: ['drizzle-kit'],
    envVars: [{ name: 'DATABASE_URL', hint: 'Postgres connection string — never commit the real value' }],
    files: [
      { path: 'drizzle.config.ts', content: DRIZZLE_CONFIG },
      { path: '.vibe/starters/database/schema.ts', content: DRIZZLE_STARTER },
    ],
    note: 'Versioned migrations only: drizzle-kit generate + migrate.',
  },

  // ---- Auth -------------------------------------------------------------
  'better-auth/better-auth': {
    install: ['better-auth'],
    envVars: [{ name: 'BETTER_AUTH_SECRET', hint: 'Strong random secret (openssl rand -hex 32)' }],
    files: [{ path: '.vibe/starters/auth/auth-setup.ts', content: BETTER_AUTH_STARTER }],
    note: 'Session cookies: httpOnly + secure + sameSite; never log tokens.',
  },
  'nextauthjs/next-auth': {
    install: ['next-auth'],
    envVars: [
      { name: 'AUTH_SECRET', hint: 'Strong random secret (openssl rand -hex 32)' },
      { name: 'NEXTAUTH_URL', hint: 'Canonical URL of the app (e.g. https://app.example.com)' },
    ],
    files: [{ path: '.vibe/starters/auth/auth-setup.ts', content: NEXT_AUTH_STARTER }],
    note: 'Prefer database sessions; rotate AUTH_SECRET on any suspected leak.',
  },

  // ---- Payments ---------------------------------------------------------
  'stripe/stripe-node': {
    install: ['stripe'],
    envVars: [
      { name: 'STRIPE_SECRET_KEY', hint: 'sk_live_… in production, sk_test_… in development' },
      { name: 'STRIPE_WEBHOOK_SECRET', hint: 'whsec_… from the Stripe webhook endpoint' },
    ],
    files: [{ path: '.vibe/starters/payments/stripe-webhook.ts', content: STRIPE_STARTER }],
    note: 'Always verify webhook signatures; use idempotency keys on charges.',
  },

  // ---- Security (binary tools — installed only with explicit consent) ---
  'gitleaks/gitleaks': {
    binary: {
      name: 'gitleaks',
      brew: 'gitleaks',
      notes: 'Full 150+ rule secret detection for the pre-commit hook (fallback patterns already installed).',
    },
  },
  'google/osv-scanner': {
    binary: {
      name: 'osv-scanner',
      brew: 'osv-scanner',
      notes: 'Multi-ecosystem CVE scanning via OSV.dev (complements npm audit).',
    },
  },

  // ---- MCP --------------------------------------------------------------
  'modelcontextprotocol/servers': {
    files: [
      {
        path: '.mcp.json',
        content: `${MCP_CONFIG_NOTE}{
  "mcpServers": {
    "filesystem": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem", "."]
    },
    "memory": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-memory"]
    },
    "fetch": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-fetch"]
    }
  }
}
`,
      },
      {
        path: '.vibe/starters/mcp/cursor-mcp.json',
        content: `// Starter generated by VibeHarness — merge into Cursor's MCP settings
// (Settings → MCP → Add new global MCP server) if you use Cursor.
{
  "mcpServers": {
    "filesystem": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem", "."]
    },
    "memory": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-memory"]
    }
  }
}
`,
      },
    ],
    note: 'Curated MCP servers configured for your agent — review each server before trusting it.',
  },

  // ---- Deploy (accounts live outside the repo — config guidance only) ---
  'coollabsio/coolify': {
    envVars: [
      { name: 'COOLIFY_URL', hint: 'Your Coolify instance URL (self-hosted PaaS)' },
      { name: 'COOLIFY_API_TOKEN', hint: 'API token from Coolify — treat as a secret' },
    ],
    note: 'Deployment target — connect the repo in the Coolify dashboard; no code changes needed.',
  },
};
